name: 'cargo-audit-check'
description: 'Run cargo audit on your project'
inputs:
  deny:
    description: 'exit with an error on: warnings (any), unmaintained, unsound, yanked'
    required: false
    default: 'warnings'
  level:
    description: 'set the tracing output level: TRACE,INFO,WARN,ERROR,FAIL'
    required: false
    default: 'INFO'
runs:
  using: 'docker'
  image: 'Dockerfile'