name: 'cargo-audit-check'
description: 'Run cargo audit on your project'
inputs:
  token:
    description: 'Your github token, which will allow issue creation'
    required: true
  deny:
    description: 'exit with an error on: warnings (any), unmaintained, unsound, yanked'
    required: false
    default: 'warnings'
  level:
    description: 'set the tracing output level: TRACE,INFO,WARN,ERROR,FAIL'
    required: false
    default: 'INFO'
  create_issue:
    description: 'create an issue when a RUSTSEC warning is found'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.deny }}
    - ${{ inputs.level }}
    - ${{ inputs.create_issue }}