[package]
authors = ["Jason Ozias <jason.g.ozias@gmail.com>"]
categories = ["development-tools"]
description = "Github Action to run 'cargo audit' on your Rust project"
documentation = "https://docs.rs/audit-check"
edition = "2024"
homepage = "https://github.com/rustyhorde/audit-check"
keywords = ["cargo", "audit", "github", "actions"]
license = "MIT OR Apache-2.0"
name = "audit-check"
readme = "README.md"
repository = "https://github.com/rustyhorde/audit-check"
version = "0.1.2"

[features]
unstable = []

[dependencies]
anyhow = "1.0.102"
regex = "1.12.3"
reqwest = { version = "0.13.2", default-features = false, features = ["rustls", "brotli", "json"] }
rustc_version = "0.4.1"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
time = { version = "0.3.47", features = ["formatting"] }
tokio = { version = "1.50.0", features = ["rt-multi-thread"] }
tracing = { version = "0.1.44", features = ["max_level_trace", "release_max_level_trace"] }
tracing-subscriber = { version = "0.3.23", features = ["time"] }

[build-dependencies]
rustversion = "1.0.22"

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ target }-v{ version }.tar.gz"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "tgz"

[package.metadata.binstall.overrides.x86_64-pc-windows-msvc]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ target }-v{ version }.zip"
pkg-fmt = "zip"
