[package]
authors = ["Jason Ozias <jason.g.ozias@gmail.com>"]
categories = ["development-tools"]
description = "Github Action to run 'cargo audit' on your Rust project"
documentation = "https://docs.rs/audit-check"
edition = "2021"
homepage = "https://github.com/rustyhorde/audit-check"
keywords = ["cargo", "audit", "github", "actions"]
license = "MIT OR Apache-2.0"
name = "audit-check"
readme = "README.md"
repository = "https://github.com/rustyhorde/audit-check"
version = "0.1.0"

[dependencies]
anyhow = "1.0.68"
reqwest = { version = "0.11.13", default-features = false, features = ["rustls-tls", "brotli", "json", "trust-dns"] }
rustc_version = "0.4.0"
serde = { version = "1.0.152", features = ["derive"] }
thiserror = "1.0.38"
time = { version = "0.3.17", features = ["formatting"] }
tokio = { version = "1.24.1", features = ["rt-multi-thread"] }
tracing = { version = "0.1.37", features = ["max_level_trace", "release_max_level_trace"] }
tracing-subscriber = { version = "0.3.16", features = ["time"] }

[build-dependencies]
rustversion = "1.0.11"
